encoder: conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of audio_encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # audio_encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 15
    use_cnn_module: True
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'

decoder: paraformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0



tokenizer: bpe
tokenizer_conf:
  symbol_table_path: '/ssd/zhuang/code/wenet/examples/librispeech/s0/data/lang_char/train_960_unigram5000_units.txt'
  split_with_space: false
  bpe_path: '/ssd/zhuang/code/wenet/examples/librispeech/s0/data/lang_char/train_960_unigram5000.model'
  non_lang_syms_path: null
  is_multilingual: false
  num_languages: 1
  special_tokens:
    <blank>: 0
    <unk>: 1
    <sos>: 2
    <eos>: 2

ctc: ctc
ctc_conf:
  ctc_blank_id: 0

cmvn: global_cmvn
cmvn_conf:
  cmvn_file: "/ssd/zhuang/code/wenet/examples/librispeech/s0/data/train_960/global_cmvn"
  is_json_cmvn: true

model: paraformer
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
  sampling_ratio: 0.75

predictor: paraformer_predictor
predictor_conf:
  cnn_groups: 1
  idim: 256
  l_order: 1
  noise_threshold2: 0.01
  r_order: 1
  residual: false
  smooth_factor2: 0.25
  tail_threshold: 0.45
  threshold: 1.0
  upsample_times: 3


# dataset related
dataset: asr
dataset_conf:
    filter_conf:
        max_length: 2000
        min_length: 50
        token_max_length: 400
        token_min_length: 1
        min_output_input_ratio: 0.0005
        max_output_input_ratio: 0.1
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 12

grad_clip: 5
accum_grad: 4
max_epoch: 120
log_interval: 100
monitor: loss
save_n: 10

optim: adam
optim_conf:
    lr: 0.004
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
